global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'fastapi'
    metrics_path: /metrics
    static_configs:
      - targets: ['fastapi:8000']

  - job_name: 'airflow'
    # Airflow may provide prometheus metrics via plugin — for simplicity we'll scrape the webserver
    static_configs:
      - targets: ['airflow:8080']
